"""
This is a setup.py script generated by py2applet

Usage:
    python setup.py py2app
"""

from setuptools import setup

APP = ['Gridlink.py']
DATA_FILES = ['../gridlink/doc/gridlink.html']
OPTIONS = {'argv_emulation': True, 'iconfile': 'gridlink.icns'}

setup(
    app=APP,
    data_files=DATA_FILES,
    options={'py2app': OPTIONS},
    setup_requires=['py2app'],
)
